[packages.apt]
    to_remove = ["btop", "htop"]
    [packages.apt.common]
        packages = [
            "apt-transport-https",
            "bat",                 # cat with syntax highlighting and Git integration
            "curl",
            "dnsutils",
            "fd-find",
            "figlet",
            "fzf",
            "git",
            "git-extras",
            "gnupg",
            "gpg",
            "jq",
            "logrotate",
            "lolcat",
            "mc",                  # Midnight Commander
            "nano",
            "ncdu",                # NCurses Disk Usage
            "needrestart",
            "net-tools",
            "openssh-server",
            "p7zip-full",
            "ripgrep",             # search tool like grep and the silver searcher
            "sudo",
            "tzdata",
            "unzip",
            "wget",
            "zsh",
        ]
[packages.python]
    to_remove = []
    [packages.python.common]
        packages = ["halper", "pygments"]
    [packages.python.dev_computer]
        packages = ["ansible-core", "cookiecutter"]
    [packages.python.homelab_member]
        # 'GITEA_ADDRESS' is overwritten by the 'gitea_address' secret
        packages = ["git+GITEA_ADDRESS/natelandau/usrbin"]
    [packages.python.personal_computer]
        packages = ["vid-cleaner"]
[packages.homebrew]
    # to_remove = ["btop", "htop", "istat-menus", "qlimagesize", "rocket", "shotrr"]
    [packages.homebrew.common]
        casks = [
            "1password-cli",                     # Text expander
            "git-credential-manager",
        ]
        formulae = [
            "atuin",           # Better shell history
            "bash",
            "bash-completion",
            "bat",             # cat with syntax highlighting and Git integration
            "bottom",          # Process/system monitor for the terminal.
            "chezmoi",         # Dotfile manager
            "coreutils",
            "eza",             # ls replacement
            "fd",              # fd-find
            "findutils",       # GNU find, locate, updatedb, and xargs
            "fzf",             # Fuzzy finder
            "gawk",            # GNU awk
            "git",
            "git-delta",       # https://github.com/dandavison/delta
            "gnu-sed",         # GNU implementation of the famous stream editor
            "gnu-tar",         # GNU version of the tar archiving utility
            "gnutls",          # GNU Transport Layer Security (TLS) Library
            "gping",           # Ping, but with a graph
            "grep",
            "jq",              # Lightweight and flexible command-line JSON processor
            "mas",             # Mac App Store command-line interface
            "mc",              # Midnight Commander
            "most",            # Pager
            "nano",
            "ncdu",            # NCurses Disk Usage
            "ncurses",         # Text-based UI library
            "openssl",         # SSL/TLS cryptography library
            "rip2",            # A safer, rust-based rm
            "ripgrep",         # search tool like grep and the silver searcher
            "sqlite3",
            "ssh-copy-id",     # Add a public key to a remote machine's authorized_keys file
            "tealdeer",        # TLDR man pages
            "tree",            # Display directories as trees (with optional color/HTML output)
            "uv",              # Python Pyenv, pipx, and packagging replacement
            "vivid",           # https://github.com/sharkdp/vivid
            "wget",
            "zoxide",          # A faster way to navigate your filesystem
            "zsh",
        ]
    [packages.homebrew.homelab_member]
        casks    = []
        formulae = ["ffmpeg", "iperf", "nmap", "tailspin"]
